### ISSUE TITLE
Undefined behavior caused by out-of-bounds accesses and invalid shifts

### ISSUE THREAD

**Issue by zyedidia** [aengelke/disarm#3]
The following instructions cause out-of-bounds accesses when formatted:

```
0x08207c1f
0x3ca0f800
0x5ac01800
0xd800001f
```

The following instructions cause invalid left shifts when decoded:

```
0x10800000
0x28200000
0x30800000
0x50800000
0x68a00000
0x70800000
0x90800000
0xa8200000
0xb0800000
0xd0800000
0xf0800000
```

Here is an example test program to run one of the examples:

```
#include <stdio.h>

#include "disarm64.h"

int main() {
    char fmtbuf[128];
    uint32_t insn = 0xd800001f;
    struct Da64Inst dinst;
    da64_decode(insn, &dinst);
    da64_format(&dinst, fmtbuf);
    printf("%s\n", fmtbuf);

    return 0;
}
```

I compiled with `-fsanitize=address,undefined`. Let me know if you'd like more info.

**Comment by aengelke** [comment]
Thanks for reporting, all mentioned cases should be fixed now.
